import os
os.getcwd()
f=open('dee.txt','w')
f.write('hey young man how are you')
f.close()
# f=open('dee.txt','r')
# print(f.read())
f.close()
f=open('dee.txt','w')
f.write('i am your friend')
f.close()
f=open('dee.txt','a')
f.write('whats your name dear please tell me')
f.close()
